# Site settings
title: Great New Blog Title
author:
  name: Christian Niederauer
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
